### ISSUE TITLE
Deduplication v2

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/embl-adapter#10]
### Additions to the existing processing of the sequence data
1. When querying sequence data from the EMBL API, add a filter to exclude CONTIGs. E.g [query=country="*"%20AND%20dataclass!="CON"](https://www.ebi.ac.uk/ena/portal/api/search?result=sequence&format=json&limit=100&query=country=%22*%22%20AND%20dataclass!=%22CON%22&fields=accession,location,country,identified_by,collected_by,collection_date,specimen_voucher,sequence_md5,scientific_name,tax_id,altitude,sex,description) to get data where country exists, but not CONTIGs.
2. Add `sample_accession` to `fields` in the query. see: https://github.com/gbif/embl-adapter/blob/master/DATAMAPPING.md#example-queries
3. You need to add a "seen before" filter when you iterate through the data. If a record has a `sample_accession` you should check if you have already seen the same `sample_accession` AND the `scientific_name` in a previous record. Could probably just be a HashMap (you dont need to store the records, just the combination of `sample_accession` AND `scientific_name`). If the combination was seen before, skip the the record

### Additional data / New query 
1. Use the same API queries as with `result=sequence` but set `result=wgs_set`
2. You have to remove `sequence_md5` from fields (not present in this result format)
3. This data should be added to the above/existing data (replacing what was filtered out by the CON filter)

**Comment by timrobertson100** [comment]
Following review, we still observe too many "duplicates" for this to be sensible in GBIF. Can we please add a filter that will exclude records that are of type `material_sample` (i.e. no vouchered specimen in a museum) AND are missing a date OR location.

**Comment by ManonGros** [comment]
Despite our best effort, this doesn't seem to be enough to remove all the "duplicates". Here are some examples of records that are very suspicious:
* https://www.gbif-uat.org/occurrence/search?dataset_key=10628730-87d4-42f5-b593-bd438185517f&taxon_key=8405827
* https://www.gbif-uat.org/occurrence/search?country=JP&dataset_key=10628730-87d4-42f5-b593-bd438185517f&month=5&taxon_key=1938088&year=2005

There are also records that correspond to the same specimens. For example: https://www.gbif-uat.org/occurrence/search?catalog_number=MSB:Mamm:250248&dataset_key=10628730-87d4-42f5-b593-bd438185517f&taxon_key=5218864&advanced=1

**Proposed solution**
1. Aggregate the records that have the same catalogue number (`specimen_voucher`)
2. Check the number of records grouped by species/date/location. If we have more than 1,000 records for a given species at a given date and location, I would suggest to exclude them from the import.
> This number (1,000 records) is completely arbitrary. That being said, it seems to me that a research project being able to sequence more than a 1,000 individuals of the same species at the same place is probably quite rare. It is possible that there could be big colonies of very small species living in the same place, and each individual of that colony would be sequenced. But I have never heard of such case. Please someone correct me if I am wrong.

**Comment by dschigel** [comment]
Deduplication of records at such scale is like renovation, one can only approach perfection asymptotically. Marie's suggestion above sounds like a pragmatic way forward, and if constructive feedback comes we would be able to revisit this.

**Comment by mike-podolskiy90** [comment]
> Check the number of records grouped by species/date/location. If we have more than 1,000 records for a given species at a given date and location, I would suggest to exclude them from the import.

@ManonGros what is `species` field here please? `tax_id` ?

**Comment by ManonGros** [comment]
Yes `tax_id` or `scientific_name`, I think that they should give the same result in the end.

**Comment by mike-podolskiy90** [comment]
Thank you. This approach actually complicate things since we write record by record

**Comment by mike-podolskiy90** [comment]
> I would suggest to exclude them from the import
Only one should be left? Or exclude all of them?

**Comment by dschigel** [comment]
Hm, this is not easy. As Marie says, 1000 is an artificial cut-off. We use as a sign of suspected duplication. Total exclusion at import sounds too harsh, but flattening 1000+ -> 1 will have a funny effect on the 999- counts

**Comment by ManonGros** [comment]
OK so after checking and debating, here is what we want:

### Step 1: use the deduplication method created by EMBL:

https://github.com/gbif/embl-adapter/issues/10#issue-876414407

### Step 2: remove records that are missing information

Record has a `specimen_voucher` = KEEP
Record had a date and location (coordinates and/or country) = KEEP
Everything else = exclude

### Step 5: Aggregate the records per `specimen_voucher`

We should have 1 record per specimen_voucher. I assume that we should use an extension to encompass the information corresponding to each EMBL entry. @thomasstjerne what would you recommend?

### Step 4: Group the records left and exclude some of the groups based on number of records

1. Group the records per `scientific_name`, `collection_date`, `location`,`country`,`identified_by`, `collected_by`
2. If the number of record per group is above a threshold, exclude them.

Given the distribution of the data and in attempt to not exclude to many records, we decided that the **threshold = 50**. See plot below:
![distribution_records_embl](https://user-images.githubusercontent.com/7677271/120990462-e106e980-c780-11eb-9424-4abfd584b166.png)

**Comment by thomasstjerne** [comment]
The only field that could be stored in an extension is `sample_accession `. Instead I added that to the grouping in step 4.1 which would produce occurrences for each unique materialSampleID.
We can introduce an extension at a later stage, as this would require an additional api call per sequence.
