### ISSUE TITLE
Splitting into several datasets depending on sample type

### ISSUE THREAD

**Issue by ManonGros** [gbif/embl-adapter#4]
We could use the he fields “environmental_sample” and “host” fields to split the data. Users will probably want to know whether a bacteria comes from the water of a river or the guts of a fish.

We could have:
* a dataset for eDNA: environmental_sample=True
* a dataset for organism sequenced: environmental_sample=False & host=“”
* a dataset with hosts? If so, we have to think about how to model this (these are probably questions for https://github.com/tdwg/dwc-qa if there aren't already guidelines for that):
    * should the host be an occurrence as well?
    * how do we map the relationship between host and sequence organism?
    * Should we use the fields associatedOccurrences or associatedOrganisms for example?

**Comment by timrobertson100** [comment]
This makes good sense to me.

**Comment by timrobertson100** [comment]
Can we please try and create the 3 datasets as described above and index them in UAT, in addition to the current one so we have something concrete to discuss. It is possible we'll then apply different deduplication processes on each type.

**Comment by mike-podolskiy90** [comment]
@ManonGros I'm going to create those on UAT. Do we have any title preference please?

**Comment by ManonGros** [comment]
I don't have a particularly strong feeling about the titles but I suggest something like that:

- INSDC sequences from environmental samples
- INSDC sequences associated with hosting organisms
- INSDC sequences - excluding environmental samples and sequences associated with host organisms

For the last one, we can only infer that they correspond to sequenced organism, it could also be that people just didn't bother to fill in the metadata. That's why I phrased it like that.

**Comment by ManonGros** [comment]
Thanks @mike-podolskiy90 !

Here are my comments:

1. For the [INSDC sequences associated with hosting organisms](https://www.gbif-uat.org/dataset/768eeb1f-a208-4170-9335-2968d17c7bdc) dataset:
    -  I think we have to **show the host organism**. As far as I understand, there is no standard way to do this at the moment.
        - I imagine that using a [resourceRelationship](https://dwc.tdwg.org/terms/#resourcerelationship) extension would be the most Darwin Core proper thing to do.
        - I can also see that we could use the [associatedTaxa](https://dwc.tdwg.org/terms/#dwc:associatedTaxa) term.
        - And there is always the [dynamicProperties](https://dwc.tdwg.org/terms/#dwc:dynamicProperties) term.
        -> I suggest to use both the [associatedTaxa](https://dwc.tdwg.org/terms/#dwc:associatedTaxa) term and the  [dynamicProperties](https://dwc.tdwg.org/terms/#dwc:dynamicProperties) term (`{"hostingOrganism":"Lutra lutra"}`. Would that make sense?
    - I don't think that it would be a good idea to keep human diseases. Could we consider excluding record where `host="Homo sapiens"`?
    - I also wonder whether we should include viruses. Perhaps if we exclude the human diseases we wouldn't need to exclude viruses.
2. For all three datasets, we still have the duplicate issue. See for example, the [3M pine tree records in the newest version on UAT](https://www.gbif-uat.org/occurrence/search?offset=0&basis_of_record=MATERIAL_SAMPLE&country=CA&dataset_key=10628730-87d4-42f5-b593-bd438185517f&has_coordinate=true&has_geospatial_issue=false&taxon_key=5284745&occurrence_status=present). I suggest to check https://github.com/gbif/embl-adapter/issues/3 and consider the solutions discussed to remove duplicates.
3. For all three datasets, is there any way we could include some higher taxonomy? I can see that a lot of records have no match in our taxonomy. It would be really helpful to have at least a Kingdom for example. @thomasstjerne do you know if it would be possible?
4. For all three datasets, this is more a suggestion for the mapping (https://github.com/gbif/embl-adapter/blob/master/DATAMAPPING.md). For non preserved specimens, we could include the culture_collection and/or the bio_material as catalogueNumber or include them in the [dynamicProperties](https://dwc.tdwg.org/terms/#dwc:dynamicProperties). What do you think?

**Comment by thomasstjerne** [comment]
It would require a API call for each occurrence (I guess you could memoize the response for each taxonID) to add some higher classification and is only possible through their XML service:
https://www.ebi.ac.uk/ena/browser/api/xml/2697049

**Comment by dschigel** [comment]
Nice to see the split view, I agree! A few comments to @ManonGros comments:
1. Old dream, if this would be easy, we would have so many other communities happy, too. If implemented, it would be a very nice GBIF improvement (requested by the modelling community). Note that one can simply display a host reported with the data, but TDWG IG on species interactions is working on revision of how to handle 2+ species occurrences, and interaction attribute: what I mean a quick display fix could be possible with available DwC fields, but with acceptance that we will likely need to revise / rebuild it, esp. if species interactions are part of next strategic plan. I am all in support of live experimenting.
2.  Can we anyhow try the contig_set trick as recommended by Guy, and have sub-views with and without lumping applied. Or ask them to experiment with this? Ideally we would set the call with EMBL with these three displayed and with dedup solutions at hand.
3. Previsouly with UNITE we asked the publisher to add higher taxonomy. What comes to my mind, if we can assume coordinate systems and fuzzy matches, why cannot we "guess" higher taxonomy and show that this is a GBIF guess in the issues? Skip homonyms perhaps?
4. Culture and tissue collection often have own [catalogueNumber](https://dwc.tdwg.org/terms/#dwc:catalogNumber)s, not sure anything but local IDs should be there ? To me culture collection and bio_material is very important, and it belongs to improving basis of record story.
5. Yes, we also observed viruses with Mikhail when looking at the first, undivided version. +1 for exclusion by H. sapiens, but for the blanket removal of viruses (from all GBIF?), this is a major decision that would at least need SC blessing.

**Comment by mdoering** [comment]
I think associatedTaxa is way better than dynamicProperties which is rather opaque. 

What is the reasoning behind excluding human host records and diseases? Isn't this potentially valuable? If we could get all Corona tests recorded I guess we would have some serious bias in GBIF data. But are we not used to that already with birds? I don't have a strong opinion, just trying to understand the reasoning. Assuming we would be able to filter searches by the host then.

**Comment by ManonGros** [comment]
This is really great to have the higher taxonomy, thanks @mike-podolskiy90!

Some feedback concerning the newest version of the datasets published:
1. for records that have been deduplicated, for example: https://www.gbif-uat.org/occurrence/2889240632, it would be good to include **all the corresponding accessions** in the associatedSequences and the references fields. For example: `https://www.ebi.ac.uk/ena/browser/view/KE161220 | https://www.ebi.ac.uk/ena/browser/view/KE161176 | https://www.ebi.ac.uk/ena/browser/view/KE161095 ...` It will look messy because we can have up to 3M of these but I think this is the only way we can ensure transparency.
2. For the [INSDC sequences associated with hosting organisms]() dataset, would it be possible to add the hosting organism (`host`) in the `associatedTaxa` field, something like `"host":"Lutra lutra"`?

**Comment by timrobertson100** [comment]
> It will look messy because we can have up to 3M of these but I think this is the only way we can ensure transparency.

Micro-encoding 3M values in a CSV cell will likely lead to issues including memory, timeouts on page loads etc. I'd suggest exploring an extension to capture that info with 3M rows.

**Comment by ManonGros** [comment]
@timrobertson100 I understand the issue but then we will need to decide:
1. will the "main" accession number (occurrenceID / associatedSequences / references) be chosen randomly? Or do we want to have some rule for that?
2. Which extension to use? @thomasstjerne any thought on this issue?

**Comment by ahahn-gbif** [comment]
> reasoning behind excluding human host records and diseases

An early decision to stay out of human biology, both to avoid overlap of content with the medical field (and scope creep), and to avoid ethical conundrums, esp around physical collections.

**Comment by mdoering** [comment]
Should GBIF then actively exclude [Homo sapiens](https://www.gbif.org/occurrence/search?taxon_key=2436436&occurrence_status=present)?

**Comment by thomasstjerne** [comment]
> 2. Which extension to use? @thomasstjerne any thought on this issue?

That would eventually be the https://tdwg.github.io/gbwg/dwc-mixs/dwc/extension/dna_derived_data.xml , but for the time being we haven´t got a suitable extension in production

**Comment by ahahn-gbif** [comment]
> Should GBIF then actively exclude Homo sapiens?

Yes, I still think we should. It used to be our explicit policy, I am not sure when we started to deviate from it. There is more risk for harm than possible benefit in these records. It ranges from the aforementioned scope creep over privacy violation into dubious ethnological/colonial issues.

**Comment by dschigel** [comment]
It would be important to have a written rule on this, and also for the associated taxa, as this is getting close to the work of GBIF task  group on human diseases. I agree that data on Homo sapience is out of our scope, but we e.g. will be looking at the data from the national WHO centers on incidence of mosquito bites. Mosquito is a wild species, a prime target for the task group, bite (interaction) data can be the only data we may have from such sources. Without data on mosquito target (Homo) the quality and value of such data may go down. Another example from EMBL dedup process is influenza A, bird flu. Naturally, we don't want bird flue data on humans, but how about such records from wild birds? I hope there is a reasonable rule coming that allows us to progress in the human disease area, but will protect GBIF from privacy etc. troubles associated with human data. I support a hard rule of no occurrence data on Homo sapiens, and very interested in how we will handle human associated species. This is a major relevance line already,  and it seems to grow in importance in GBIF (e.g. in GB, EC, SC discussions).

**Comment by MattBlissett** [comment]
Recent observations of people might be out of scope (although people are sharing it intentionally, and not always citizen science, e.g. https://www.gbif.org/occurrence/2426811662 ).

But shouldn't we keep specimen observations, especially fossils?  Requesting citizen science systems exclude _H. sapiens_ from their exports is probably better than filtering it out on our side.

**Comment by ahahn-gbif** [comment]
Fossils (like the Cro Magnon records) appear safe enough, but e.g. ethnological specimen collections (or even photos) are already back in a territory that needs careful consideration of ethics codes

**Comment by mdoering** [comment]
And what about records for neanderthalensis? I opened a backbone ticket for it as we have quite a few unmatched occurrences: https://github.com/gbif/checklistbank/issues/169

**Comment by ahahn-gbif** [comment]
Probably safe to assume those are mostly fossil. As the backbone goes, better to have extinct taxa in (and whatever records are maintained matched properly) than linked at species level. All just my personal take.

**Comment by ManonGros** [comment]
> > 1. Which extension to use? @thomasstjerne any thought on this issue?
> 
> That would eventually be the https://tdwg.github.io/gbwg/dwc-mixs/dwc/extension/dna_derived_data.xml , but for the time being we haven´t got a suitable extension in production

So what should we do about all the accession numbers corresponding to the duplicates? Should we ignore them for now?

**Comment by thomasstjerne** [comment]
Use this extension https://rs.gbif.org/extension/ggbn/amplification.xml and add their full URI in `geneticAccessionURI`
